name: example
description: Examples for assorted_layout_widgets
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  assorted_layout_widgets:
    path: ../
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
