name: assorted_layout_widgets
description: Assorted layout widgets that boldly go where no native Flutter widgets have gone before.
version: 1.1.0
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/assorted_layout_widgets

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  matrix4_transform: any
  flutter:
    sdk: flutter

